spring:
  security:
    oauth2:
      client:
        registration:
          client1:
            provider: spring
            clientId: client-1
            clientSecret: secret
            clientName: client-1-name
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: "http://127.0.0.1:8082/login/oauth2/code/{registrationId}"
            scope:
              - "products.read"
              - "products.write"
              - "openid"
        provider:
          spring:
            issuer-uri: http://localhost:8080

server:
  port: 8082
logging:
  level:
    org.springframework.security: trace
