spring:
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithms: RS256 #default
          issuer-uri: http://keycloak:8080/realms/spring-realm
server:
  port: 8081
