spring:
  security:
    oauth2:
      client:
        registration:
          kc-client:
            client-id: kc-client
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8082/login/oauth2/code/kc-client
            client-authentication-method: client_secret_basic
            client-secret: MqJdl8r90is291Vx5aQDapIo4SIkdMWw
            scope:
              - "openid"
              - "products.read"
              - "products.write"
        provider:
          kc-client:
            issuer-uri: http://keycloak:8080/realms/spring-realm
            user-name-attribute: preferred_username

server:
  port: 8082
logging:
  level:
    org.springframework.security: trace
management:
  endpoints:
    web:
      exposure:
        include: health