spring:
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithms: RS256 #default
          public-key-location: classpath:rs256.key.pub #single key

